api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from api.views import CompanyViewSet

router = DefaultRouter()
router.register(r'company', CompanyViewSet, basename='company')

urlpatterns = [
    path('', include(router.urls)),
]

companies/urls.py
from django.urls import path

from . import views

app_name = 'companies'

urlpatterns = [
  path('', views.CompanyList.as_view(), name='company_list'),
  path('new/', views.CompanyCreate.as_view(), name='company_new'),
  path('edit/<int:pk>/', views.CompanyUpdateView.as_view(), name='company_edit'),
  path('delete/<int:pk>/', views.CompanyDelete.as_view(), name='company_delete'),
  path('company/<int:pk>', views.CompanyDetailView.as_view(), name='company_detail'),
]

crud_service/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView

from accounts import views


urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('companies/', include('companies.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
    # drf-spectacular:
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('api/', include('api.urls')),
	#path to djoser end points
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

companies/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse_lazy


class Company(models.Model):
    """Company model"""
    title = models.CharField('Название', max_length=50)
    description = models.TextField('Информация о компании', max_length=500, blank=True)
    news = models.TextField('Новости компании', blank=True)
    foundation_date = models.DateField('Дата основания: YYYY-mm-dd', null=True, blank=True)
    avatar = models.ImageField('Аватар', upload_to='company/%Y/%m/%d/', blank=True)

    def __str__(self):
        return '{}'.format(self.title)

    def get_absolute_url(self):
        return reverse_lazy('companies:company_detail', kwargs={'pk': self.pk})

    # Компания заглушка 'No company'
    @classmethod
    def create_stub_company(cls, title='No company'):
        company = cls(title=title)
        return company

    class Meta:
        verbose_name = "Company"
        verbose_name_plural = "Companies"

companies/forms.py
from django import forms

from companies.models import Company


class ModeratorEditForm(forms.ModelForm):
    """Moderator edit form"""

    class Meta:
        model = Company
        fields = ['description', 'news', 'foundation_date', 'avatar']


class UserEditForm(forms.ModelForm):
    """User edit form"""

    class Meta:
        model = Company
        fields = ['news']


class AdminEditForm(forms.ModelForm):
    """Admin edit form"""

    class Meta:
        model = Company
        fields = '__all__'

companies/views.py
from django.contrib.auth.mixins import AccessMixin
from django.http import HttpResponseForbidden
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .forms import ModeratorEditForm, UserEditForm, AdminEditForm
from .models import Company


class EditCompanyPermissionsMixin(AccessMixin):

    # Только пользователи и модераторы компании могут изменять портфолио своей компании
    def dispatch(self, request, *args, **kwargs):
        if request.user.profile.is_admin or self.user_has_permissions(request):
            return super(EditCompanyPermissionsMixin, self).dispatch(
                request, *args, **kwargs)

        return HttpResponseForbidden("You do not have permission to Edit Company Profile")

    def user_has_permissions(self, request):
        return self.request.user.profile.company.pk == self.kwargs['pk']


class DeleteCompanyPermissionsMixin(AccessMixin):

    # Только is_admin может удалять компании
    def dispatch(self, request, *args, **kwargs):
        if request.user.profile.is_admin:
            return super(DeleteCompanyPermissionsMixin, self).dispatch(
                request, *args, **kwargs)

        return HttpResponseForbidden("You do not have permission to Delete Company Profile")


class CompanyList(ListView):
    context_object_name = 'companies'
    model = Company

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.exclude(title__iexact='No company')


class CompanyCreate(CreateView):
    model = Company
    fields = ['title', ]
    success_url = reverse_lazy('companies:company_list')


class CompanyUpdateView(EditCompanyPermissionsMixin, UpdateView):
    model = Company
    success_url = reverse_lazy('companies:company_list')

    # Разнные формы изменения портфолио компании
    # для разных ролей пользователей
    def get_form_class(self):
        if self.request.user.profile.is_admin:
            return AdminEditForm
        if self.request.user.profile.is_moderator:
            return ModeratorEditForm
        return UserEditForm


class CompanyDelete(DeleteCompanyPermissionsMixin, DeleteView):
    model = Company
    success_url = reverse_lazy('companies:company_list')

    # Переопределим get_queryset чтобы случайно не удалить компанию заглушку
    def get_queryset(self):
        qs = super().get_queryset()
        return qs.exclude(title__iexact='No company')


class CompanyDetailView(DetailView):
    model = Company
    template_name = 'companies/company_detail.html'
    context_object_name = 'company'

companies/templates/companies/company_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <h2>Удалить компанию: <a
            href="{% url 'companies:company_detail' company.pk %}">{{ company.title }}</a>?</h2>
    <form method="post">{% csrf_token %}
        Are you sure you want to delete "{{ object }}" ?<br>
        <input type="submit" value="Delete"/>
    </form>
{% endblock %}

companies/templates/companies/company_detail.html
{% extends "base.html" %}
{% block title %}Company - {{ company.title}}{% endblock %}
{% block content %}
    <h1>Company - {{ company.title}}</h1>
    <div>
        <ul>
            <li><p>Название компании: {{ company.title}}</p></li>
            <li><p>Описание: {{ company.description }}</p></li>
            <li><p>Новости: {{ company.news }}</p></li>
            <li><p>Дата основания: {{ company.foundation_date }}</p></li>
            <li><p>Аватар: </p>
                <p><img src="{{ MEDIA_URL }}{{ company.avatar }}" alt="{{ company.avatar }}"></p>
            </li>
        </ul>
    </div>
{% endblock %}

companies/templates/companies/company_form.html
{% extends "base.html" %}
{% block content %}
    {% if company %}
        <h2>Компания <a
                href="{% url 'companies:company_detail' company.pk %}">{{ company.title }}</a>:
        </h2>
    {% else %} <h2>Создайте компанию</h2>
    {% endif %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit"/>
    </form>
{% endblock %}

companies/templates/companies/company_list.html
{% extends "base.html" %}
{% block content %}
    <h2><a href="{% url 'companies:company_list' %}">Companies</a></h2>
    <ul>
        {% for company in companies %}
            <li><a href="{{ company.get_absolute_url }}">{{ company.title }}</a>
                {% if request.user.is_authenticated and request.user.profile.company.id is company.id or request.user.profile.is_admin %}
                    <a href="{% url 'companies:company_edit' company.id %}">edit</a>
                {% endif %}
                {% if request.user.profile.is_admin %}
                    <a href="{% url 'companies:company_delete' company.id %}">delete</a>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
    {% if request.user.profile.is_admin %}
        <a href="{% url 'companies:company_new' %}">New</a>
    {% endif %}
{% endblock %}