accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('home/', views.HomePageView.as_view(), name='home'),
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('logout/', views.LogoutUserView.as_view(), name='logout'),
    path('registration/', views.RegisterUserFormView.as_view(), name='registration'),
    path('edit/edit_done/<int:pk>', views.ProfileUpdateDoneView.as_view(), name='update_done'),
    path('edit/<int:pk>', views.ProfileUpdateView.as_view(), name='update_profile'),
    path('users/', views.ProfileListView.as_view(), name='users_list'),
    path('user/<int:pk>', views.ProfileDetailView.as_view(), name='user_detail'),
]

api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from api.views import CompanyViewSet

router = DefaultRouter()
router.register(r'company', CompanyViewSet, basename='company')

urlpatterns = [
    path('', include(router.urls)),
]

companies/urls.py
from django.urls import path

from . import views

app_name = 'companies'

urlpatterns = [
  path('', views.CompanyList.as_view(), name='company_list'),
  path('new/', views.CompanyCreate.as_view(), name='company_new'),
  path('edit/<int:pk>/', views.CompanyUpdateView.as_view(), name='company_edit'),
  path('delete/<int:pk>/', views.CompanyDelete.as_view(), name='company_delete'),
  path('company/<int:pk>', views.CompanyDetailView.as_view(), name='company_detail'),
]

crud_service/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView

from accounts import views


urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('companies/', include('companies.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
    # drf-spectacular:
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('api/', include('api.urls')),
	#path to djoser end points
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %} Test site {% endblock %}</title>
</head>
<body>
<main>
    {% block content %}{% endblock %}
</main>
<hr>
    <a href="{% url 'home' %}">Домашняя страница</a><br>
    {% if request.user.is_authenticated %}
        <a href="{% url 'accounts:update_profile' request.user.profile.pk %}">{{ request.user.username }} - Отредактируйте Ваш профиль</a><br>
        <a href="{% url 'accounts:logout' %}"> Logout</a><br>
        {% else %}
         <a href="{% url 'accounts:login' %}"> Login</a><br>
    {% endif %}
    <a href="{% url 'accounts:users_list' %}">Список зарегистрированных пользователей</a><br>
    <a href="{% url 'companies:company_list' %}">Список компаний</a><br>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block title %}Домашняя{% endblock %}
{% block content %}
    <h2>Домашняя страница</h2>
    {% if request.user.is_authenticated %}
        <h2>Здравствуйте {{ request.user.username }}</h2>
    {% endif %}
    {% if not request.user.is_authenticated %}
{#        <a href="{% url 'accounts:login' %}">Login </a>#}
{#        <p><strong>-- OR --</strong></p>#}
        <a href="{% url 'accounts:registration' %}">Зарегистрируйтесь</a><br>
{#        <a href="{% url 'social:begin' 'github' %}">Login with GitHub</a><br>#}
    {% endif %}
{#    {% if request.user.is_authenticated %}#}
{#        <a href="{% url 'accounts:logout' %}">Logout </a><br>#}
{#    {% endif %}#}
{% endblock %}